# Generated by Django 4.0.2 on 2022-02-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='total',
            new_name='total_venta',
        ),
    ]
