# Generated by Django 4.0.2 on 2022-02-19 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='metodo_pago',
            new_name='metodo_de_pago',
        ),
    ]
