# Generated by Django 4.0.2 on 2022-02-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_rename_metodo_pago_venta_metodo_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
