# Generated by Django 4.0.2 on 2022-02-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_alter_venta_iva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='subtotal_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
    ]
