# Generated by Django 4.0.2 on 2022-02-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_alter_venta_subtotal_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad_detalle',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
