# Generated by Django 4.0.2 on 2022-02-21 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0006_venta_codigo_producto_venta_nombre_producto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagina.venta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(through='pagina.detalle_venta', to='pagina.producto'),
        ),
    ]
