# Generated by Django 4.0.2 on 2022-02-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_detalle_venta_venta_venta_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='entrada_caja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='salida_caja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
