# Generated by Django 4.0.2 on 2022-02-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0009_alter_caja_entrada_caja_alter_caja_salida_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='entrada_caja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='salida_caja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_caja',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
