# Generated by Django 4.0.2 on 2022-02-22 22:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_alter_caja_entrada_caja_alter_caja_salida_caja_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='total_venta',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='precio_detalle',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cantidad_detalle',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='codigo_producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='nombre_producto_venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='subtotal_venta',
        ),
        migrations.AlterField(
            model_name='venta',
            name='codigo_cliente_venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField(null=True)),
                ('codigo_producto', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cantidad', models.IntegerField()),
                ('codigo_venta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pagina.venta')),
            ],
        ),
    ]
