# Generated by Django 4.0.2 on 2022-02-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0011_rename_total_venta_venta_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cajaDinero',
            fields=[
                ('codigo_caja_dinero', models.AutoField(primary_key=True, serialize=False)),
                ('Caja1', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
    ]
