# Generated by Django 4.0.2 on 2022-02-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0012_cajadinero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_caja',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='caja',
            name='hora_caja',
            field=models.CharField(max_length=50),
        ),
    ]
